# Site settings
title: ADSI Summer on Foundations of Data Science
email: arokem@uw.edu
baseurl: /~alecgt  # the subpath of your site, e.g. /blog
url:  www.stat.washington.edu
description: "A summer school on data science at the University of Washington"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#444444'
  links: '#e8e3d3'

# Footer settings
footer: # Ariel Rokem, UW eScience Institute

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/neurohackademy
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  #- title: github
  #  url: https://github.com/neurohackademy

# Build settings
markdown: kramdown
permalink: pretty
